# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_simulacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 300)
        self.simulacion_comboBox = QtWidgets.QComboBox(Form)
        self.simulacion_comboBox.setGeometry(QtCore.QRect(320, 50, 61, 21))
        self.simulacion_comboBox.setObjectName("simulacion_comboBox")
        self.simulacion_comboBox.addItem("")
        self.simulacion_comboBox.addItem("")
        self.simulacion_comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.upload_simulacion_pushButton = QtWidgets.QPushButton(Form)
        self.upload_simulacion_pushButton.setGeometry(QtCore.QRect(130, 130, 171, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.upload_simulacion_pushButton.setFont(font)
        self.upload_simulacion_pushButton.setObjectName("upload_simulacion_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.simulacion_comboBox.setItemText(0, _translate("Form", "forma1"))
        self.simulacion_comboBox.setItemText(1, _translate("Form", "forma2"))
        self.simulacion_comboBox.setItemText(2, _translate("Form", "forma3"))
        self.label_5.setText(_translate("Form", "Seleccione el formato de ingreso de datos:"))
        self.upload_simulacion_pushButton.setText(_translate("Form", "UPLOAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
