# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 800)
        Form.setStyleSheet("QWidget#widget{\n"
"background-color: rgb(255, 255, 255);}")
        self.ejextextEdit = QtWidgets.QTextEdit(Form)
        self.ejextextEdit.setGeometry(QtCore.QRect(130, 510, 161, 31))
        self.ejextextEdit.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"border-radius:5px;")
        self.ejextextEdit.setObjectName("ejextextEdit")
        self.ejeytextEdit = QtWidgets.QTextEdit(Form)
        self.ejeytextEdit.setGeometry(QtCore.QRect(130, 560, 161, 31))
        self.ejeytextEdit.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"border-radius:5px;")
        self.ejeytextEdit.setObjectName("ejeytextEdit")
        self.ejexlabel = QtWidgets.QLabel(Form)
        self.ejexlabel.setGeometry(QtCore.QRect(90, 510, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setBold(True)
        font.setWeight(75)
        self.ejexlabel.setFont(font)
        self.ejexlabel.setObjectName("ejexlabel")
        self.ejeylabel = QtWidgets.QLabel(Form)
        self.ejeylabel.setGeometry(QtCore.QRect(90, 560, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setBold(True)
        font.setWeight(75)
        self.ejeylabel.setFont(font)
        self.ejeylabel.setObjectName("ejeylabel")
        self.bgwidget = QtWidgets.QWidget(Form)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1251, 801))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: rgb(255, 255, 255);}")
        self.bgwidget.setObjectName("bgwidget")
        self.moduloButton = QtWidgets.QPushButton(self.bgwidget)
        self.moduloButton.setGeometry(QtCore.QRect(90, 460, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setBold(True)
        font.setWeight(75)
        self.moduloButton.setFont(font)
        self.moduloButton.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"border-radius:5px;")
        self.moduloButton.setObjectName("moduloButton")
        self.simulacionButton = QtWidgets.QPushButton(self.bgwidget)
        self.simulacionButton.setGeometry(QtCore.QRect(90, 240, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.simulacionButton.setFont(font)
        self.simulacionButton.setStyleSheet("background-color:rgb(205, 139, 224);\n"
"border-radius:15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.simulacionButton.setObjectName("simulacionButton")
        self.checkBox_4 = QtWidgets.QCheckBox(self.bgwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(480, 50, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.bgwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(630, 50, 70, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.bgwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(770, 50, 70, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.MplWidget = MplWidget(self.bgwidget)
        self.MplWidget.setGeometry(QtCore.QRect(480, 130, 675, 300))
        self.MplWidget.setObjectName("MplWidget")
        self.MplWidget2 = MplWidget(self.bgwidget)
        self.MplWidget2.setGeometry(QtCore.QRect(480, 440, 675, 300))
        self.MplWidget2.setObjectName("MplWidget2")
        self.mostrar_teorico_Button = QtWidgets.QPushButton(self.bgwidget)
        self.mostrar_teorico_Button.setGeometry(QtCore.QRect(300, 130, 75, 23))
        self.mostrar_teorico_Button.setStyleSheet("background-color:rgb(88, 224, 173);\n"
"border-width: 2px;\n"
"border-color: black;\n"
"border-radius:50px;")
        self.mostrar_teorico_Button.setObjectName("mostrar_teorico_Button")
        self.ocultar_teorico_Button = QtWidgets.QPushButton(self.bgwidget)
        self.ocultar_teorico_Button.setGeometry(QtCore.QRect(300, 180, 75, 23))
        self.ocultar_teorico_Button.setStyleSheet("background-color:rgb(88, 224, 173);\n"
"border-radius:15px;\n"
"\n"
"border-width: 2px;\n"
"border-color: black;")
        self.ocultar_teorico_Button.setObjectName("ocultar_teorico_Button")
        self.ocultar_simulacion_pushButton = QtWidgets.QPushButton(self.bgwidget)
        self.ocultar_simulacion_pushButton.setGeometry(QtCore.QRect(300, 290, 75, 23))
        self.ocultar_simulacion_pushButton.setStyleSheet("background-color:rgb(205, 139, 224);\n"
"\n"
"border-radius:15px;\n"
"\n"
"border-width: 2px;\n"
"border-color: black;")
        self.ocultar_simulacion_pushButton.setObjectName("ocultar_simulacion_pushButton")
        self.mostrar_simulacion_pushButton = QtWidgets.QPushButton(self.bgwidget)
        self.mostrar_simulacion_pushButton.setGeometry(QtCore.QRect(300, 240, 75, 23))
        self.mostrar_simulacion_pushButton.setStyleSheet("background-color:rgb(205, 139, 224);\n"
"\n"
"border-radius:15px;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.mostrar_simulacion_pushButton.setObjectName("mostrar_simulacion_pushButton")
        self.ocultar_medicion_pushButton = QtWidgets.QPushButton(self.bgwidget)
        self.ocultar_medicion_pushButton.setGeometry(QtCore.QRect(300, 400, 75, 23))
        self.ocultar_medicion_pushButton.setStyleSheet("background-color:rgb(224, 177, 65);\n"
"border-radius:15px;\n"
"\n"
"border-width: 2px;\n"
"border-color: black;")
        self.ocultar_medicion_pushButton.setObjectName("ocultar_medicion_pushButton")
        self.mostrar_medicion_pushButton = QtWidgets.QPushButton(self.bgwidget)
        self.mostrar_medicion_pushButton.setGeometry(QtCore.QRect(300, 350, 75, 23))
        self.mostrar_medicion_pushButton.setStyleSheet("background-color:rgb(224, 177, 65);\n"
"border-radius:15px;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.mostrar_medicion_pushButton.setObjectName("mostrar_medicion_pushButton")
        self.teoricoButton = QtWidgets.QPushButton(Form)
        self.teoricoButton.setGeometry(QtCore.QRect(90, 130, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.teoricoButton.setFont(font)
        self.teoricoButton.setStyleSheet("background-color:rgb(88, 224, 173);\n"
"border-radius:15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.teoricoButton.setObjectName("teoricoButton")
        self.medicionButton = QtWidgets.QPushButton(Form)
        self.medicionButton.setGeometry(QtCore.QRect(90, 350, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.medicionButton.setFont(font)
        self.medicionButton.setStyleSheet("background-color:rgb(224, 177, 65);\n"
"border-radius:15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.medicionButton.setObjectName("medicionButton")
        self.faseButton = QtWidgets.QPushButton(Form)
        self.faseButton.setGeometry(QtCore.QRect(220, 460, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setBold(True)
        font.setWeight(75)
        self.faseButton.setFont(font)
        self.faseButton.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"border-radius:5px;")
        self.faseButton.setObjectName("faseButton")
        self.borrarpushButton = QtWidgets.QPushButton(Form)
        self.borrarpushButton.setGeometry(QtCore.QRect(90, 630, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.borrarpushButton.setFont(font)
        self.borrarpushButton.setStyleSheet("background-color:rgb(148, 119, 50);\n"
"border-radius:15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.borrarpushButton.setObjectName("borrarpushButton")
        self.bgwidget.raise_()
        self.ejextextEdit.raise_()
        self.ejeytextEdit.raise_()
        self.ejexlabel.raise_()
        self.ejeylabel.raise_()
        self.teoricoButton.raise_()
        self.medicionButton.raise_()
        self.faseButton.raise_()
        self.borrarpushButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ejexlabel.setText(_translate("Form", "Eje X:"))
        self.ejeylabel.setText(_translate("Form", "Eje Y:"))
        self.moduloButton.setText(_translate("Form", "Módulo"))
        self.simulacionButton.setText(_translate("Form", "SIMULACIÓN"))
        self.checkBox_4.setText(_translate("Form", "Curva 1"))
        self.checkBox_5.setText(_translate("Form", "Curva 2"))
        self.checkBox_6.setText(_translate("Form", "Curva 3"))
        self.mostrar_teorico_Button.setText(_translate("Form", "Mostrar"))
        self.ocultar_teorico_Button.setText(_translate("Form", "Ocultar"))
        self.ocultar_simulacion_pushButton.setText(_translate("Form", "Ocultar"))
        self.mostrar_simulacion_pushButton.setText(_translate("Form", "Mostrar"))
        self.ocultar_medicion_pushButton.setText(_translate("Form", "Ocultar"))
        self.mostrar_medicion_pushButton.setText(_translate("Form", "Mostrar"))
        self.teoricoButton.setText(_translate("Form", "TEORICO"))
        self.medicionButton.setText(_translate("Form", "MEDICIÓN"))
        self.faseButton.setText(_translate("Form", "Fase"))
        self.borrarpushButton.setText(_translate("Form", "BORRAR\n"
"GRÁFICOS"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
